import { Container, Header } from '@/shared/components/shared'
import { Suspense } from 'react'

export const metadata = {
  title: 'Next Pizza ',
  description: 'Generated by Next.js',
}

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="min-h-screen">
      <Container>
        <Suspense>
          <Header
          />
        </Suspense>
        {children}
      </Container>
    </main>
  )
}
